spring.application.name=purchase-transaction-service
# Application properties for the Purchase Transaction Service
# Uncomment and configure the following properties as needed. Values provided are defaults and can be overridden.
#rates.of.exchange.base-url=https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange
#rates.of.exchange.fields=record_date,country,currency,exchange_rate,effective_date
#rates.of.exchange.page-size=100
#rates.of.exchange.months-to-look-back=6